version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6543:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis_db
    ports:
      - "6379:6379"
  app:
    container_name: grading-service
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8090"
    depends_on:
      - postgres
      - redis
    environment:
      CONFIG_PATH: ./config/
volumes:
  postgres-data: