DROP TABLE IF EXISTS roles;

DROP TABLE IF EXISTS marks;

DROP TABLE IF EXISTS student_lesson;

DROP TABLE IF EXISTS lessons;

DROP TABLE IF EXISTS teachers;

DROP TABLE IF EXISTS students;

DROP TABLE IF EXISTS users;

